Initial Commit
bosagora/bosagora-foundation-api pull request #1
Opened 2023-01-06 09:02 UTC by TrustHenry

2023-01-09 05:36 UTC, MichaelKim20 requested changes
확인해주세요

2023-01-09 05:36 UTC, MichaelKim20 commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            CommonsBudgetBalance = CommonsBudgetBalance.div(BigNumber.from(10 ** 9));
```suggestion
            CommonsBudgetBalance = CommonsBudgetBalance.div(BigNumber.from(10 ** 11));
```

2023-01-09 05:36 UTC, MichaelKim20 commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            let CirculatingSupply = this.InitialSupply.sub(
음수가 나올수 있기 때문에 먼저 
TotalSupply = InitialSupply + RewardBalance + CommonsBudgetBalance - BurnedBalance 를 먼저 계산합니다.
CirculatingSupply = TotalSupply - (FoundationBalance + MarketingBalance + BridgeLiquidity + BridgeFoundationLiquidity + TeamMemberBalance + HoledAirdropBalance + CommonsBudgetBalance)

2023-01-09 05:36 UTC, MichaelKim20 commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            const FoundationBalance = BigNumber.from(await this.BOAcontract.balanceOf(this.FoundationAddress));
재단 소유의 보아는 이미 모두 스테이킹 되어 deposit contract로 예치되었습니다.
따라서 재단주소에서 조회한 값을 사용하지 마시고 그냥 40,000,000 BOA로 고정해 주세요

2023-01-09 06:16 UTC, TrustHenry commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            CommonsBudgetBalance = CommonsBudgetBalance.div(BigNumber.from(10 ** 9));
The sugestion applied.

2023-01-09 06:16 UTC, TrustHenry commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            const FoundationBalance = BigNumber.from(await this.BOAcontract.balanceOf(this.FoundationAddress));
this.BridgeFoundationLiquidity = BigNumber.from("400000000000000");
        해당 금액은 위와 같이 정의 되어있습니다.

2023-01-09 06:31 UTC, TrustHenry commented on src/service/schedulers/SupplyAPIScheduler.ts
> +            let CirculatingSupply = this.InitialSupply.sub(
The sugestion applied.

2023-01-10 03:23 UTC, MichaelKim20 commented on src/service/schedulers/SupplyAPIScheduler.ts
> +        console.log(`On start`);
```suggestion
        console.log(`On start`);
        await this.work();
```

스케줄러가 시작되면서 바로 잔고를 조회해서 유통량과 발행량을 집계하도록 하면 비정상적인 데이타를 제공하는 경우를 줄일수 있겠습니다.

2023-01-10 04:25 UTC, TrustHenry commented on src/service/schedulers/SupplyAPIScheduler.ts
> +        console.log(`On start`);
The sugestion applied.

2023-01-10 04:27 UTC, MichaelKim20 approved these changes
LGTM

2023-01-10 04:27 UTC, merged