Changing Reward Calculations for Withdrawal Upgrades
bosagora/bosagora-foundation-api pull request #4
Opened 2023-07-21 06:30 UTC by TrustHenry

2023-07-21 06:52 UTC, Kang-Simon approved these changes
LGTM

2023-07-24 01:07 UTC, MichaelKim20 requested changes

2023-07-24 01:07 UTC, MichaelKim20 commented on src/service/schedulers/SupplyAPIScheduler.ts
> +        const SQL = "SELECT SUM(total_balance) - SUM(effectivebalance) as reward FROM public.validator_balances_p b WHERE b.epoch = (SELECT MAX(epoch) epoch FROM public.epochs e)";
```suggestion
        const SQL = "SELECT SUM(balance) + SUM(withdrawal) - SUM(balanceactivation) as reward FROM public.validators";
```

2023-07-24 02:00 UTC, TrustHenry commented on src/service/schedulers/SupplyAPIScheduler.ts
> +        const SQL = "SELECT SUM(total_balance) - SUM(effectivebalance) as reward FROM public.validator_balances_p b WHERE b.epoch = (SELECT MAX(epoch) epoch FROM public.epochs e)";
반영 하였습니다.

2023-07-24 04:32 UTC, MichaelKim20 approved these changes
LGTM

2023-07-24 04:34 UTC, merged